name: flutter_unity_widget_example_arkit
description: Demonstrates how to use the flutter_unity_widget plugin with ARKIT.
publish_to: 'none'

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  flutter_unity_widget: ^0.1.6+5
  flutter_unity_widget: ^2022.1.0+5
  #  flutter_unity_widget: 4.1.0
  flutter_svg: ^0.22.0
  web_socket_channel: ^2.2.0
  firebase_core: ^1.19.1
  firebase_database: ^9.0.18
  socket_io_client: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^0.1.2


flutter:
  uses-material-design: true

